ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Проект «Ботан» — чат-бот для ЯрГУ

image:https://travis-ci.com/uniyar/uniyar_bot.svg?token=W5qvsmB7w8wq6nMrt2GC&branch=master["Build Status", link="https://travis-ci.com/uniyar/uniyar_bot"]

== Общее описание проекта

Задача чат-бота — создать иллюзию. Иллюзию того, что пользователь разговаривает с кем-то, с кем-то кто понимает и обдумывает сказанное. Конечно чат-бот не думает. Тем не менее, некоторое время можно поддерживать это ощущение. Как достичь такой иллюзии? Об этом этот проект.

*Цель проекта* состоит в создании системы, которая сочетает по крайней мере две функции: информирующую и развлекающую.

Участникам предстоит разработать виртуальную личность со своими интересами, переживаниями и знаниями. Биографические факты должны переплетаться с информационной «полезной» нагрузкой. Продуманные повествования, непосредственные реакции и тонкие намёки — всё это послужит основой для поддержания интереса пользователя. Одной из важных задач будет определение перечня тем для поддержания разговора и сбор фактической информации 

Для работы над проектом потребуется:
— владение компьютером на среднем уровне;
— знание английского языка (словарный запас, чтение документов);
— ответственность.

Стек технологий, которые будут использоваться:
— Платформа: Телеграм;
— Язык программирования: Python;
— Бот-движок: ChatScript.

== Запуск в режиме разработчика

=== Предварительные действия

Для запуска кода из репозитория прежде всего необходимо, чтобы на компьютере было установлено следующее ПО:

* git — https://git-scm.com;
* docker — https://hub.docker.com/editions/community/docker-ce-desktop-windows;
* make — https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows;
* рекомендуемый текстовый редактор VS Code — https://code.visualstudio.com.

[NOTE]
.*Только для пользователей Windows*
--

Поскольку Windows не поддерживает многие необходимые команды, которые потребуется в дальнейшем, то нужно установить Cygwin. Cygwin — это набор программ (Linux команд) для Windows. Тебе необходимо поставить Cygwin и использовать его терминал для выполнения команд. 

. Скачать с http://cygwin.com/install.html[сайта Cygwin] дистрибутив, подходящий к установленной версии Windows.
. Запустить скаченный файл (`setupx84_64.exe` или типа того).
. На экране приветствия нажать «Далее».
. На экране «Choose A Download Source» выбрать «Install from Internet» и нажать «Далее».
. На экране «Select Root Install Directory» нужно оставить предложенное значение для «Root Directory» и выбрать установку для всех пользователей «All Users». Нажать «Далее».
. На экране «Select Local Package Directory» ничего не трогать. Нажать «Далее».
. На экране «Select Your Internet Connection» выбрать «Direct Connection». Нажать «Далее».
. (Действие не требуется) Cygwin загрузит список доступных зеркал (то есть серверов на которых хранится программное обеспечение Cygwin).
. На экране «Choose A Download Site» нужно выбрать какой-нибудь сайт и нажать «Далее».
. (Действие не требуется) Cygwin загрузит список доступного программного обеспечения.
. Теперь ты попал на экран «Select Packages». Выбери из выпадающего списка «View» в верхнем левом углу «Full» вместо «Category». Больше ничего не трогать.
. Для каждого перечисленных ниже пакетов нажми на надпись «Skip», чтоб выбрать этот пакет для установки. Поиск пакета удобно осуществлять с помощью строки поиска «Search». При нажатии на «Skip» надпись должна превращаться в номер версии пакета, типа `2.1.4-1`. Возможно некоторые пакеты уже будут выбраны для установки, тогда нажимать ничего не надо.
+
[cols="1,3"]
|===
|Пакет | Описание
|bash | THE GNU Bourne Again SHell
|git | Distributed version control system
|make | |

|===
. Нажми «Далее» для проверки списка установки.
. На экране «Resolving Dependencies» удостоверься, что выбран пункт «Select required packages» и нажми «Далее».
. (Действие не требуется) Cygwin установит все выбранные пакеты.
. На экране «Create Icons» лучше выбрать оба пункта «Desktop icons» и «Start Menu icons», чтобы было легче отыскать «Cygwin Terminal». Нажми «Finish» для завершения.

Все последующие команды следует вводить в терминале «Cygwin Terminal».
--

Следующим шагом необходимо клонировать этот репозиторий на локальную машину:

----
git clone https://github.com/uniyar/uniyar_bot.git
----

В текущей папке появится подпапка `uniyar_bot` с программным кодом. Зайди в неё:

----
cd uniyar_bot
----

В репозитории существует две ветки: главная ветка `master` и рабочая ветка `dev`. Сейчас не важно что это за ветки такие. Главное запомнить, что работа ведётся с веткой `dev`. На неё и надо перейти командой:

----
git checkout dev
----

Теперь открывай папку в текстовом редакторе. В случае использования VS Code:

----
code .
----

=== Описание репозитория

Описание составляющих:

Директорий `botan` :: содержит код на языке Python, обеспечивающий взаимодействие между Telegram и ChatScript.
Директорий `chatscript` :: содержит скрипты бота (top-файлы), именно в соответствии с этими файлами бот реагирует на воздействия.
Директорий `log` :: сюда будут складываться логи ботана.
Директорий `test` :: содержит автоматизированные тесты для кода в `botan`.
Файл `config.yaml` :: настройки для `botan`.

=== Настройки

В файле `config.yaml` отсутствуют необходимые данные для взаимодействия с Telegram и c Yandex Translate. Файл `config.yaml` представляет собой пример, для запуска нужно создать файлы `config.dev.yaml` (работа в режиме разработчика) или `config.prod.yaml`(работа в боевом режиме).
Содержимое этих файлов может вполне совпадать с предложенным `config.yaml`, однако следует заменить следующие поля:

* `telegram.api_token`;
* `yandex_translate.api_key`.

==== Получение telegram.api_token

Все боты в телеграме управляются специальным ботом с именем `@BotFather`. Для того, чтобы получить возможность запускать свою версию ботана нужно зарегистрировать в `@BotFather` своего ботана (он будет запускаться только с твоего компьютера, но будет доступен через телеграм на обычных основаниях).

. В телеграме найди `@BotFather` и начни с ним разговор.
. Введи команду `/newbot`.
. В ответ на вопрос об имени бота напиши так: `Ботан (debug-<твой username>)`.
. В ответ на вопрос о юзернейме бота напиши так: `botan_debug_<твой username>_bot`.
. Всё! `@BotFather` возвратит информацию о регистрации, в том числе требуемую строку (после слов `Use this token to access the HTTP API:`).
. Эту строку и надо вписать в конфигурационный файл.

==== Получение yandex_translate.api_key

Для получения этого ключа следует быть зарегистрированным на `yandex.ru`. Для генерации ключа следует зайти на `https://translate.yandex.ru/developers/keys` и нажать кнопку «Создать новый ключ». Полученную строку добавить в конфигурационный файл.

=== Полноценный локальный запуск

Для запуска требуется наличие конфигурационного файла `config.prod.yaml`. Запуск осуществляется из корневой папки репозитория командой:

----
$ docker-compose up
----

Если всё прошло нормально, то зарегистрированный тобой в `@BotFather` телеграм-бот сможет отвечать.



